"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const db_1 = require("./db");
exports.default = db_1.RealTimeDB;
var db_2 = require("./db");
exports.RealTimeDB = db_2.RealTimeDB;
exports.FirebaseBoolean = db_2.FirebaseBoolean;
var firebase_api_surface_1 = require("firebase-api-surface");
exports.rtdb = firebase_api_surface_1.rtdb;
exports.auth = firebase_api_surface_1.auth;
